### ISSUE TITLE
Adding more fields

### ISSUE THREAD

**Issue by nicksav** [MichaelSolati/geofirestore#1]
Guys, I am still trying to get my head around, but as I understand technically you can add more fields into stored obj? 
As you are using sorting and start At and End At in filetrs, could be good to save more fields and pass more filters inside. Am I correct?

**Comment by MichaelSolati** [comment]
@morrislaptop as long as it passes tests I'd say that I'm open. I mean it was something I was looking to do over the next week or two (wanted to have this up by the end of the month), however it'll require some planning on my end.

**Comment by Nexuist** [comment]
Just wanted to say that I was planning on working on a PR that fixes this tonight and @morrislaptop just beat me to it. Great job! 🥇

**Comment by MichaelSolati** [comment]
Hey guys while I appreciate the PR I think I'm going to be writing this myself. In my head I have a vision/ideas where I want this to go... And it will be a hard departure from how `geofire` worked. But I think you guys will like it! I'll be pushing code tomorrow for y'all to peak into it. It should be good.

**Comment by morrislaptop** [comment]
Could you merge in with a feature version and make your changes in a major version?

**Comment by MichaelSolati** [comment]
@morrislaptop possibly, let me fix the tests and then see if it passes. If yes, then sure, but I'll have to get back to you on that by tomorrow night.

**Comment by MichaelSolati** [comment]
Because the tests are failing it's not going to auto deploy, I'll have to deploy version 1.1 sometime this week (be excited!)

**Comment by morrislaptop** [comment]
Sweet! I think this will get a lot of users over from realtime / geofire over here!

**Comment by MichaelSolati** [comment]
Version `1.1.1` is up on NPM and should work! (Make sure you don't install `1.1.0`, it had a kinda major issue where it accidentally deleted the distribution code on postinstall 😅)

**Comment by MvRemmerden** [comment]
In 1.1.1 and 1.2.0 there was a setWithDocument() method, which I assume is what was being talked about here, right? But it got killed off in 2.0.0, was there any reason for it? It would solve the biggest problem I'm facing right now.

**Comment by MvRemmerden** [comment]
That's amazing, had totally not seen that in the readme, thanks for clarifying!

**Comment by Leuchapolo** [comment]
I noticed that the above code makes it so the coordinates are stored both in the data as well as the coordinate attribute. Is there a way to add without making the coordinates be added to data as well aside from just deleting it immediately?

**Comment by MichaelSolati** [comment]
@Leuchapolo because we don't track the field you use to store the coordinates, we need to store it in order to do client side checks of the distance (to filter out places). Unfortunately it is needed.
