### ISSUE TITLE
Problems setting GeoPoint

### ISSUE THREAD

**Issue by PlamenSh** [MichaelSolati/geofirestore#15]
I was having problems with setting locations
`geoFirestore.set('some_key', { coordinates: new firebase.firestore.GeoPoint(37.79, -122.41)})`
giving: "Invalid GeoFire location '[object Object]': location must be an array"

using this instead solved it:
`geoFirestore.set(userId, [42.497855, 27.470660])`

Using: 
geofirestore@1.2.0
firebase@4.10.0

**Comment by MichaelSolati** [comment]
You're looking at the docs for v2 😅 not 1.2.0. Try `npm i geofirestore@next` to try the version 2 beta (it's pretty much ready to launch, I just need to expand typing support for `firebase-admin`)
