### ISSUE TITLE
Importing GeoFirestore causes error about `self.fetch`

### ISSUE THREAD

**Issue by jimmykwok** [MichaelSolati/geofirestore#17]
Adding `import { GeoFirestore } from 'geofirestore'` causes my react native app to crash:

`undefined is not an object (evaluating 'self.fetch')`

Seems like it is related with [this issue](https://github.com/facebook/react-native/issues/9599), but the fix does not work for me. Has anyone run into the same problem?

Versions:
```
"react-native": "0.55.4",
"geofirestore": "^2.0.1",
```

**Comment by MichaelSolati** [comment]
`geofirestore` is designed to be used for the web, and uses the `firebase` web library. Can you share any more of your code or dependencies?

**Comment by MichaelSolati** [comment]
Ok, I'm going to try making a custom build of `geofirestore`, where I'll ask that you take the file and replace the folder you have in your `node_modules` folder and use it. If it works, I'll launch it as version 2.0.1. My email is available on my GitHub profile, please contact me that way and we will go from there.

**Comment by MichaelSolati** [comment]
So I'll need a little more time to get a proper/working build. I just cloned a sample react native app, I did an npm link, and I'm testing tweaks and builds to get it to work for me. Once I do that I'll reply to all of you who have reached out to me via email and we can go from there. IF anyone has experience bundling packages for react native please let me know (help is always appreciated).

**Comment by MichaelSolati** [comment]
@jimmykwok version 2.0.2 should have fixed this issue (due to a massive build issue). Please try installing it and let me know how that goes. (If I don't hear anything back in the next day or so I will close this issue)

**Comment by jimmykwok** [comment]
Great! your version 2.0.2 fix works for me. Thanks!
