### ISSUE TITLE
collectionRef must be an instance of a firestore collection

### ISSUE THREAD

**Issue by kingtross88** [MichaelSolati/geofirestore#20]
I keep getting the following error messages. I'm running firebase version "version": "5.3.0". Can you please let me know what i'm doing wrong? My code is below. The error stems from the first line.

 const collectionRef = firebase.firestore().collection('Locations')
  const geoFirestore = new GeoFirestore(collectionRef);
  const geoQuery = geoFirestore.query({
  center: new firebase.firestore.GeoPoint(this.state.region.latitude, this.state.region.longitude),
  radius: 10.5
  });

    const center = geoQuery.center();
    geoQuery.on('ready', () => {
      });

    geoQuery.on('key_entered', function (key, document, distance) {
      console.log(key + ' entered query at ' + document.coordinates.latitude + ',' + document.coordinates.longitude + ' (' + distance + ' km from center)');
    });

    geoQuery.on('key_exited', function (key, document, distance) {
      console.log(key + ' exited query to ' + document.coordinates.latitude + ',' + document.coordinates.longitude + ' (' + distance + ' km from center)');
      // removeMarker(key); // To remove a marker if you wanted
    });

    geoQuery.on('key_moved', function (key, document, distance) {
      console.log(key + ' moved within query to ' + document.coordinates.latitude + ',' + document.coordinates.longitude + ' (' + distance + ' km from center)');
    });

    geoQuery.on('key_modified', function (key, document, distance) {
      console.log(key + ' in query has been modified');
    });

**Comment by MichaelSolati** [comment]
Is this a web app or on the server? (A screenshot would be awesome too)

**Comment by kingtross88** [comment]
this is a react native app. Is this code server based code only?


![screen shot 2018-08-03 at 12 34 51 pm](https://user-images.githubusercontent.com/6825383/43654644-e496c8c6-9719-11e8-9b79-9369e6832de2.png)

**Comment by MichaelSolati** [comment]
Could I possibly see the full file? Unfortunately it'll be hard for me to troubleshoot like this as I have used geofirestore with React Native without issue (as have others), so I need to find what the difference is and go from there. Is your project a public one? (or one you could share with me in private?)

**Comment by kingtross88** [comment]
I've placed the code below.

`import React, { Component } from 'react';
import {
  Text,
  View,
  StyleSheet,
  TouchableHighlight,
  Image,
  FlatList,
  ScrollView,
  Dimensions,

} from 'react-native';

import { FormLabel, FormInput, FormValidationMessage, Button, Header, Icon} from 'react-native-elements';
import { StackNavigator, DrawerNavigator } from 'react-navigation';
import StarRating from 'react-native-star-rating';
import styles from './common-styles';
import MapRentals from './MapRentals';
import firebase from 'firebase';
import Home from './Home';
import { GeoFirestore } from "geofirestore";
import renderIf from './renderIf';
import 'firebase/firestore';


export default class MapRentalsList extends Component {
 
 static navigationOptions = {
    header: null
  }

   constructor(props){
    super(props);
    this.state = {
      collection:[], 
      loading: true,
    };
    this.ref = firebase.firestore().collection('Parking_Spots');
    this.unsubscribe = null;
  }

  componentDidMount() {
     firebase.auth().signInWithEmailAndPassword("kstross88@gmail.com", "welcome1").then(function(success) {   
        }).catch(e => {
          alert(e)
        });
   this.getCurrentPosition();
   this.unsubscribe = this.ref.onSnapshot(this.onCollectionUpdate);

  }

  componentWillUnmount() {
      this.unsubscribe();
  }

  getCurrentPosition(){
     navigator.geolocation.getCurrentPosition((position) => {
        region = {
          latitude: position.coords.latitude,
          longitude: position.coords.longitude,
          latitudeDelta:  0.00922,
          longitudeDelta: 0.00421,
          error: null,
        }
        this.setState({
        region,
      });
    },
    (error) => this.setState({ error: error.message }),
    { enableHighAccuracy: true, timeout: 20000, maximumAge: 1000 },

    );
  }


   goToMapView(){
    this.props.navigation.navigate('MapRentals');
  }

  


  onCollectionUpdate = (querySnapshot) => {
  const collection = [];
  let that = this;

  querySnapshot.forEach((doc) => {
    const { rating, address, bicycle, car, firebaseID, hourlyRate, imageURL2, imageURL3, mainPhotoURL, latitude, longitude, motorcycle, nickName, photoIDURL, spaces, truck} = doc.data();
    collection.push({
      key: doc.id,
      nickName: doc.data().d.nickName,
      address: doc.data().d.address, 
      mainPhotoURL: doc.data().mainPhotoURL, 
      hourlyRate: doc.data().d.hourlyRate, 
      car: doc.data().d.car, 
      truck: doc.data().d.truck,
      bicycle: doc.data().d.bicycle,
      motorcycle: doc.data().d.motorcycle,
      spaces: doc.data().d.spaces,
      rating: doc.data().rating,
    });
  });
  that.setState({ 
    collection,
    loading: false,
 });
  this.grabGeoFire();
}




grabGeoFire(){
  const collectionRef = firebase.firestore().collection('Parking_Spots')
  const geoFirestore = new GeoFirestore(collectionRef);
  const geoQuery = geoFirestore.query({
  center: new firebase.firestore.GeoPoint(this.state.region.latitude, this.state.region.longitude),
  radius: 10.5
  });

    const center = geoQuery.center();
    geoQuery.on('ready', () => {
      });

    geoQuery.on('key_entered', function (key, document, distance) {
      console.log(key + ' entered query at ' + document.coordinates.latitude + ',' + document.coordinates.longitude + ' (' + distance + ' km from center)');
    });

    geoQuery.on('key_exited', function (key, document, distance) {
      console.log(key + ' exited query to ' + document.coordinates.latitude + ',' + document.coordinates.longitude + ' (' + distance + ' km from center)');
      // removeMarker(key); // To remove a marker if you wanted
    });

    geoQuery.on('key_moved', function (key, document, distance) {
      console.log(key + ' moved within query to ' + document.coordinates.latitude + ',' + document.coordinates.longitude + ' (' + distance + ' km from center)');
    });

    geoQuery.on('key_modified', function (key, document, distance) {
      console.log(key + ' in query has been modified');
    });

}

    bookSpot(){
       const geoFirestore = new GeoFirestore(this.ref);
  const geoQuery = geoFirestore.query({
  center: new firebase.firestore.GeoPoint(this.state.region.latitude, this.state.region.longitude),
  radius: 10.5
  });

    const center = geoQuery.center();
    geoQuery.on('ready', () => {
      });

    geoQuery.on('key_entered', function (key, document, distance) {
      console.log(key + ' entered query at ' + document.coordinates.latitude + ',' + document.coordinates.longitude + ' (' + distance + ' km from center)');
    });

    geoQuery.on('key_exited', function (key, document, distance) {
      console.log(key + ' exited query to ' + document.coordinates.latitude + ',' + document.coordinates.longitude + ' (' + distance + ' km from center)');
      // removeMarker(key); // To remove a marker if you wanted
    });

    geoQuery.on('key_moved', function (key, document, distance) {
      console.log(key + ' moved within query to ' + document.coordinates.latitude + ',' + document.coordinates.longitude + ' (' + distance + ' km from center)');
    });

    geoQuery.on('key_modified', function (key, document, distance) {
      console.log(key + ' in query has been modified');
    });
    }



  renderRow(rowData) {

    const { width, height } = Dimensions.get('window')
    const iconInfo = rowData.item.car
    let that = this;

  return (
    <View style={{height: 250, marginLeft: 15, marginRight: 15, marginTop: 20, backgroundColor: 'white'}}>
              <View style={{height: 150, marginRight: 0, marginLeft: 0,}}>
                  <Image source={{uri: rowData.item.mainPhotoURL}}
                    resizeMode='cover'
                     style={{flex:1, width: null, height: null}}/>
              </View>
              <View style={{flex: 1,}}>
                  <View style={{flexDirection: 'row', justifyContent: 'space-between'}}>
                  <Text style={{fontSize:16, marginTop: 5, marginLeft: 10,}}>
                  {rowData.item.nickName}
                  </Text>
                  <Text style={{fontSize: 16, color: 'green', marginRight: 5, fontWeight: 'bold'}}>
                  {'$' + rowData.item.hourlyRate}
                  </Text>
                  </View>
                  <Text style={{fontSize:14, marginTop: 5, marginLeft: 10,}}>
                  {rowData.item.address}
                  </Text>
                  <View style={{marginTop: 5, flexDirection: 'row', justifyContent: 'space-between'}}>
                  <View style={{width: 100, height: 20, }}>
                  <StarRating
                    disabled={true}
                    maxStars={5}
                    emptyStarColor='white'
                    rating={rowData.item.rating}
                    starSize={16}
                    containerStyle={{marginLeft: 10}}
                    emptyStarColor='grey'
                    fullStarColor="yellow"/>
                  <View style={{width: 150, height: 20, flexDirection: 'row', }}>
                     {rowData.item.car ?
                      <Icon
                      reverse
                      name='car'
                      size={10}
                      type='font-awesome'
                      color='#517fa4'/>
                      :
                      <View>
                         {/* this is an empty view to display nthing if vehicle tpe isn't permitted.*/}
                      </View>
                    }
                    {rowData.item.suv ?
                    <Icon
                      reverse
                      name='truck'
                      size={10}
                      type='font-awesome'
                      color='#517fa4'/>
                      :
                      <View>
                      </View>
                    }
                    {rowData.item.bicycle ?
                    <Icon
                    reverse
                    name='bicycle'
                    size={10}
                    type='font-awesome'
                    color='#517fa4'/>
                    :
                      <View>

                      </View>
                    }
                    {rowData.item.motorcycle ?
                    <Icon
                    reverse
                    size={10}
                    name='motorcycle'
                    type='font-awesome'
                    color='#517fa4'/>
                    :
                      <View>

                      </View>
                    }
                    </View>
                  </View>
                  <Button
                    backgroundColor='green'
                    rounded={true}
                    color='white'
                    onPress={this.bookSpot}  
                    style={{width: 100, width: 80}}
                    title='Book!'/>
                  </View>
              </View>
            </View>
          )
  }


  render() {
    const { navigate } = this.props.navigation;
    return (
      <View style={styles.listViewPage}>
      <TouchableHighlight onPress={this.goToMapView} underlayColor={'transparent'}>
        <Text style={styles.listViewTitle}>
        {'<'} MapView
        </Text>
        </TouchableHighlight>
      <FlatList data={this.state.collection} 
                keyExtractor={(item, index) => item.key}
                renderItem={this.renderRow.bind(this)} 
                enableEmptySections={true}/> 
      </View>
    );
  }
}



`

**Comment by MichaelSolati** [comment]
Having ripped apart the code I can't see anything wrong. I will need to ask that you make a very basic repository with this issue in order for me to test it. Without that I will not be able to move forward (and will close out the issue without it in a few days).

**Comment by kingtross88** [comment]
totally understood. I'll do so.

Thank you for the quick response!

**Comment by kingtross88** [comment]
figured it out. I think I just needed some time away from the computer. I forgot to add "new GeoFirestore(collectionRef);".

It's working now. 

Thank you!
