### ISSUE TITLE
Cannot find namespace 'FirebaseFirestore'.

### ISSUE THREAD

**Issue by MvRemmerden** [MichaelSolati/geofirestore#22]
After updating to 2.1.0., the following error appears: `Cannot find namespace 'FirebaseFirestore'.`

I was able to fix it by changing FirebaseFirestore.CollectionReference to typesWeb.CollectionReference in the following lines:

`export namespace cloud {
  export interface CollectionReference extends FirebaseFirestore.CollectionReference { }
}`

I have created PR to fix this issue. #23

**Comment by MichaelSolati** [comment]
Oy vey! @MvRemmerden  that may not work for the cloud functions. Shoot, I'll get on this right away (thank you for making me aware)

**Comment by MvRemmerden** [comment]
Ah, makes sense, I was just testing out the firestore queries, not the cloud functions. And no worries, always happy to help :)

**Comment by MvRemmerden** [comment]
![screen shot 2018-08-07 at 09 24 03](https://user-images.githubusercontent.com/18680169/43760922-c8874d24-9a23-11e8-9d33-11e6390b275b.png)

TypeScript 2.6.2

**Comment by MichaelSolati** [comment]
Fascinating, I'm not getting this. Mind you I'm on Typescript 3.0.1... Hrmm, ok, I can try and work from this!

**Comment by MvRemmerden** [comment]
Just updated to Typescript 3.0.1, still same error. Might be due to my project running on Ionic and with AngularFire2.

**Comment by MichaelSolati** [comment]
Yea, that didn't fix it, I'll have to try more tomorrow in the morning. Ughhh, sorry for the inconvenience!

**Comment by MvRemmerden** [comment]
No worries, it's not an inconvenience at all, as I don't need the cloud functions and can just continue with my forked version.

**Comment by MichaelSolati** [comment]
Try `npm i MichaelSolati/geofirestore#dev`, I've tried it with a few different projects and a few different versions of Typescript. If I get a yes that works I'll be deploying it to NPM today!

**Comment by MvRemmerden** [comment]
Sorry for the late reaction, yes it works!
