### ISSUE TITLE
TypeError: snapshot.docChanges is not a function at... 

### ISSUE THREAD

**Issue by kenzdozz** [MichaelSolati/geofirestore#27]
@MichaelSolati  

I get this Error with 
    "firebase-admin": "^6.0.0",
    "geofirestore": "^2.1.1"

TypeError: snapshot.docChanges is not a function at /home/kenzdozz/WebDev/Gigasec/Node/needtest/node_modules/geofirestore/dist/index.cjs.js:925:26 at watch.onSnapshot (/home/kenzdozz/WebDev/Gigasec/Node/needtest/node_modules/@google-cloud/firestore/build/src/reference.js:1531:13) at push (/home/kenzdozz/WebDev/Gigasec/Node/needtest/node_modules/@google-cloud/firestore/build/src/watch.js:533:17) at DestroyableTransform.stream.on.proto (/home/kenzdozz/WebDev/Gigasec/Node/needtest/node_modules/@google-cloud/firestore/build/src/watch.js:560:25) at DestroyableTransform.emit (events.js:182:13) at addChunk (/home/kenzdozz/WebDev/Gigasec/Node/needtest/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:291:12) at readableAddChunk (/home/kenzdozz/WebDev/Gigasec/Node/needtest/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:278:11) at DestroyableTransform.Readable.push (/home/kenzdozz/WebDev/Gigasec/Node/needtest/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:245:10) at DestroyableTransform.Transform.push (/home/kenzdozz/WebDev/Gigasec/Node/needtest/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:148:32) at DestroyableTransform.afterTransform (/home/kenzdozz/WebDev/Gigasec/Node/needtest/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:91:10)

You can reproduce it from this repo 
https://github.com/kenzdozz/needtest

**Comment by MichaelSolati** [comment]
Coolio, I'll take a look at this in the next day or two. Thank you for opening an issue!

**Comment by kenzdozz** [comment]
@MichaelSolati any heads up on this?

**Comment by MichaelSolati** [comment]
@kenzdozz will the Firebase admin doesn't have proper typing support for some of the things I'm dependent on like collectionreferences as well as documentchanges I'm having a hard time trying to get a build that will work with these things. As of now unfortunately nothing. But I am still working on this!

**Comment by MichaelSolati** [comment]
@kenzdozz oooh... => https://github.com/MichaelSolati/geofirestore/tree/fix/firebase-admin

**Comment by kenzdozz** [comment]
Thanks for the update, I will try it out.

**Comment by MichaelSolati** [comment]
@kenzdozz let me know how/if it works!

**Comment by kenzdozz** [comment]
:+1: :+1: :+1: :1st_place_medal: :100: 
Thanks @MichaelSolati 
It's working great.
Thanks again!!!

**Comment by kenzdozz** [comment]
I am building a web project which shares same data with a mobile app. The mobile app uses this [https://github.com/imperiumlabs/GeoFirestore-Android](url) but the document structure is different.
I had to make some adjustments to some files to get the two platforms to share the same data.

**Comment by MichaelSolati** [comment]
@kenzdozz I'd love to know/see some of those differences (but i'm happy things worked out)

**Comment by MichaelSolati** [comment]
Fixed w/ v2.1.2

**Comment by kenzdozz** [comment]
On [GeoFirestore-Android](https://github.com/imperiumlabs/GeoFirestore-Android), the document is saved together with the location data and not as data.d.
Also, the location is not saved as Geopoint object, but as array.

I created a gist for the changes I made...
[Check it here](https://gist.github.com/kenzdozz/084cf75567ade70b5128a2f2e3a532ec)
