### ISSUE TITLE
Can't find variable: document

### ISSUE THREAD

**Issue by CoderHuzaifa** [MichaelSolati/geofirestore#28]
I am getting this strange issue:  
![whatsapp image 2018-08-20 at 1 01 33 am](https://user-images.githubusercontent.com/9552894/44312623-a76c6480-a414-11e8-8958-2f81408cd61b.jpeg)

"dependencies": {
    "firebase": "^5.4.0",
    "geofirestore": "^2.1.1",
    "geolib": "^2.0.24",
    "react": "16.3.1",
    "react-native": "0.55.4",
    "react-native-elements": "^0.19.1",
    "react-native-fbsdk": "^0.7.0",
    "react-native-firebase": "^4.3.8",
    "react-native-google-signin": "^1.0.0-rc3",
    "react-native-maps": "^0.21.0",
    "react-native-material-textfield": "^0.12.0",
    "react-native-navigation": "^1.1.480",
    "react-native-vector-icons": "^5.0.0"
  }

import  firebase from 'firebase';
import 'firebase/firestore';
import { GeoFirestore } from "geofirestore";

I can't figure out how to resolve this issue. Any help would be appreciated.

Thanks

**Comment by MichaelSolati** [comment]
@CoderHuzaifa a sample project would be appreciated, I won't be able to troubleshoot without one 😅

**Comment by CoderHuzaifa** [comment]
I solved this issue by downgrading to firebase 5.0.3
`yarn add firebase@5.0.3`

I used these imports statements:

**Comment by MichaelSolati** [comment]
@CoderHuzaifa which version of firebase were you on?

**Comment by MichaelSolati** [comment]
Errr, those import statements seem off/odd. I'd retry it as such.
```
import * as firebase from 'firebase/app';
import 'firebase/firestore';
import 'firebase/auth';
```

Otherwise I'm happy to hear you've got it working (now), mind you I need to find out why any issues popped up with `5.4.0`.
