### ISSUE TITLE
geofirestore__WEBPACK_IMPORTED_MODULE_5___default.a is not a constructor

### ISSUE THREAD

**Issue by MikeJWms** [MichaelSolati/geofirestore#29]
Hi,

I'm getting the error `geofirestore__WEBPACK_IMPORTED_MODULE_5___default.a is not a constructor`

Originally seen in a nuxt app I'm working on, and reproduced in a vue cli 3 default app for testing. Also tried downgrading firebase to v5.0.3 like another person had luck with - no luck for me.

The vue cli 3 test project can be found [here](https://github.com/MikeJWms/geotest). The relevant code is inside the HelloWorld.vue component, [here](https://github.com/MikeJWms/geotest/blob/master/src/components/HelloWorld.vue).

Thanks for your work on this library! Hopefully this is a quick fix.

**Comment by MichaelSolati** [comment]
@MikeJWms the way that you're importing firebase and geofirestore are off, try changing lines 8->10 to this
```
import * as firebase from 'firebase/app';
import 'firebase/firestore' //if use firestore
import {GeoFirestore} from 'geofirestore'
```

**Comment by MikeJWms** [comment]
Awesome, thanks for the quick response!
