### ISSUE TITLE
Only cached results when persistence enabled

### ISSUE THREAD

**Issue by dramentol** [MichaelSolati/geofirestore#31]
Hi,

It looks like query returns only cached results if firestore persistence is enabled.

It would be nice to be able to pass options like "source: server", "source: cache"... like firestore [query.get](https://firebase.google.com/docs/reference/js/firebase.firestore.GetOptions?authuser=2).

**Comment by MichaelSolati** [comment]
This library only exists as a wrapper to enable geoqueries on firestore. Unfortunately this feature request doesn't fall in line with the intended goals of this library.

**Comment by dramentol** [comment]
Well, this is not a feature request, it's a bug.

Geofirestore only return cached results if persistence enabled.

**Comment by MichaelSolati** [comment]
Geofirestore doesn't advertise or claim persistence, that's a feature of firestore. Geofirestore only provides a wrapper to allow for geoqueries. I'm not sure how that would be considered a bug for geofirestore. Allowing persistence of firestore seems to resolve this issue.

**Comment by MichaelSolati** [comment]
I think I misunderstood/misunderstand the core of your issue. I'll look into this more today, but I think you may be right (and I was being an idiot).

**Comment by dramentol** [comment]
@MichaelSolati thank you

**Comment by dramentol** [comment]
@MichaelSolati Thanks a lot, works perfect.

**Comment by dramentol** [comment]
Hi, @MichaelSolati, this is happening again.
