### ISSUE TITLE
Query sometimes returns no results from the same input

### ISSUE THREAD

**Issue by MarcL** [MichaelSolati/geofirestore#33]
Hello!

Firstly, a big thanks for creating this library for Firestore. I've used the `geofire` library for the realtime database so it's great that it's been recreated for Firestore. Your work is much appreciated.

I've written some geohashed data to Firestore and I'm querying it using the `geoFirestore.query()` method. It mostly works but on some occasions it fails to trigger the `key_entered` event even though the query is currently hard-coded for testing.

Here's the code:
![query-code](https://user-images.githubusercontent.com/1965510/45601958-27ceb700-ba0d-11e8-899c-c76678b248c1.png)

Am I missing something obvious with the way the geohashing works? I can't understand why it doesn't return the same data each time as the initial query doesn't change.

Thanks,
Marc

**Comment by MarcL** [comment]
Thanks @MichaelSolati. Here's an image of the data in my database:

<img width="1154" alt="screen shot 2018-09-17 at 09 05 31" src="https://user-images.githubusercontent.com/1965510/45612064-a2252880-ba59-11e8-97f4-c56162e96dec.png">

This only has 6 documents in the collection and I've found that it even happens with just a couple.
All of the geohashes are lowercase but not sure if there's anything I need to do in the query.

**Comment by MichaelSolati** [comment]
Ughh, ok, so this is really odd (and painful), as the tests should catch this. As this may be a nuisance, would you mind making a sample repo as minimal as possible with it not working? (This would seriously help)

**Comment by MarcL** [comment]
Hey @MichaelSolati. Thanks for investigating. I'll get this done for you today and get a simple failure case. Thanks.

**Comment by MarcL** [comment]
Try this project @MichaelSolati. It should be a basic test and I've put instructions in the README. Thanks for your help.

https://github.com/MarcL/geofirestore-test

**Comment by MichaelSolati** [comment]
Hey @MarcL, try replacing geofirestore with `npm i MichaelSolati/geofirestore`. I think I pinned down the issue (THINK), and pushed up a tweak for this. But I'd like to make sure it works for you first. (I tried running the get like 50 times after the fix and had no issues)

**Comment by MarcL** [comment]
Thanks @MichaelSolati. I've just tried the version from this repo in the test project and seems to work as expected. Thanks!

**Comment by MarcL** [comment]
@MichaelSolati - Is Firestore a lot slower than the realtime database? I'm just doing some test queries locally using the above fix and I'm seeing an average query time of ~2000 ms. I then do a similar test with the Firebase realtime database and [geofire-js](https://github.com/firebase/geofire-js) and I'm getting average query times with the same query of 400 ms. The data schema is a bit different to account for the advice on denormalisation for the realtime database, but I just wondered if there was anything obvious to speed up the Firestore queries. Thanks.

**Comment by MichaelSolati** [comment]
So I don't think I've explicitly seen anything saying that the RTDB is faster than Firestore, but I completely think that's true. The RTDB is advertised as "low-latency", while nothing is explicitly stated about Fitestore's speed...

[Looking here](https://firebase.google.com/docs/database/rtdb-vs-firestore) they don't mention anything about speed under "Reliability and performance" as well as "Scalability."

So, IMHO, you'll get speed with the RTDB, you'll get a more powerful database and queryability with Firestore.

**Comment by MarcL** [comment]
Thanks for the info. I wanted to use Firestore as I'd not used it before, and I thought it might be quicker for my queries (tagging of geohashed locations).  I'll investigate RTDB again too. Thanks for all of your help.

**Comment by MichaelSolati** [comment]
Version 2.2.1 is deployed on NPM.

**Comment by hindsricardo** [comment]
Looks like this problem now exists in version 3.3.1

**Comment by MichaelSolati** [comment]
@hindsricardo can you build a sample application with this issue persists?
