### ISSUE TITLE
Updating an existing doc

### ISSUE THREAD

**Issue by anesumuz** [MichaelSolati/geofirestore#34]
Is there a way to continually update an existing doc with new location? I think this may be a useful feature and may be able to submit a pull request.

```
geoFirestore.update(key, {
           coordinates: new firebase.firestore.GeoPoint(37.79, -122.41)
       })
```

**Comment by MichaelSolati** [comment]
The `set` function would do this for you. I'm going to close this for now, but if that doesn't do the trick let me know and we can go from there.
