### ISSUE TITLE
Range queries

### ISSUE THREAD

**Issue by Lesther993** [MichaelSolati/geofirestore#36]
Is there a way to use range queries ('<', '<=', '>', '>=') with a document field?

**Comment by MichaelSolati** [comment]
So Geofirestore SHOULD support range queries. I'd [take a look at this](https://github.com/MichaelSolati/geofirestore/blob/master/README.md#geofirestorequeryquerycriteria) for how to use a custom query.

Let me know how that goes and if I don't hear back from you I'll close this out by tomorrow.
