### ISSUE TITLE
Bug Report: ready event fires hundreds of times for one geoQuery

### ISSUE THREAD

**Issue by vpontis** [MichaelSolati/geofirestore#39]
I have one GeoFirestore instance and when I update the `queryCriteria` I get the `ready` event fired hundreds of times. 

The documentation reads:

> `ready` fires once when this query's initial state has been loaded from the server. The `ready` event will fire after all other events associated with the loaded data have been triggered. `ready` will fire again once each time `updateCriteria()` is called, after all new data is loaded and all other new events have been fired.

From this it sounds like `ready` should be called `number of updateCriteriaCalls + 1`. 

But when add `console.log` statements to `updateCriteria` and to my `ready` event handler, I get the following:

![image](https://user-images.githubusercontent.com/1319079/46322444-c6c2e980-c59d-11e8-8696-5d7087d06293.png)

Is my understanding about the `ready` event logic incorrect? Or is there a bug?

**Comment by MichaelSolati** [comment]
This may be a bug. However it may fire if data in the DB has changed. I'll have to look into this.

**Comment by MichaelSolati** [comment]
Is your Firsetore database being changed in real time as you log these events? I updated an old project of mine to (log when I update my query criteria)(https://github.com/MichaelSolati/spittin-hot-geofire/blob/642c9ec14cb1114280a871d2d6739c5a032c8f62/src/app/services/restaurants.service.ts#L23) as well as [log when the `ready` event fires](https://github.com/MichaelSolati/spittin-hot-geofire/blob/642c9ec14cb1114280a871d2d6739c5a032c8f62/src/app/services/restaurants.service.ts#L39).

As a result I'm only getting one log of each.
<img width="1680" alt="screen shot 2018-10-09 at 3 41 50 pm" src="https://user-images.githubusercontent.com/11811422/46702925-eda2a080-cbd9-11e8-8415-db3da6a3c305.png">

You can tinker with this at [https://spittin-hot-geofire.firebaseapp.com/](https://spittin-hot-geofire.firebaseapp.com/).

Let me know what's up and we can go from there.

**Comment by MichaelSolati** [comment]
Closing as this may relate to issue #38
