### ISSUE TITLE
Not working on react native project

### ISSUE THREAD

**Issue by marcoredoxigen** [MichaelSolati/geofirestore#4]
I was able to run this library in nodejs project in a console project without a problem. However, when ran it as part of a React Native project, the package and objects are loaded, however, events are not triggered when doing a query from the app running in the device.

Any guidance appreciated.

**Comment by MichaelSolati** [comment]
Possible duplicate of #3 ?

**Comment by marcoredoxigen** [comment]
Hi Michael, we did not get any error. We take the same example ran in a node JS console and port it to react native app and doesn't trigger the enter event.

**Comment by MichaelSolati** [comment]
Yea that's why I think it's worth looking at #3 which seems to be very similar if not the same issue that you're facing.

**Comment by marcoredoxigen** [comment]
ok.

Do you have an estimated when this issue can be addressed?

**Comment by MichaelSolati** [comment]
I think you'll want to look at the last two comments on #3
