### ISSUE TITLE
Question: Can this be used on an Express Server (node)?

### ISSUE THREAD

**Issue by zeuslawyer** [MichaelSolati/geofirestore#42]
Hi Michael
first up, thank you for putting together this library.  I'm pretty new to coding generally, and I appreciate how much work must go into stuff like this.

I'm trying to make this library work on an express server. I've got a firestore collection of docs that have a property with GeoPoint hashes. its a toy app, so its a collection of bars (like the example use case).  I want to retrieve a list of places within  X kms and then render a view with the places and their data being sent to the EJS page being rendered.

Is this usecase supported?   when I run the .on(key_entered, cb ) method with callback I get a couple of places but cant figure out how to get them all and then add to an array before i render the page.  

All help gratefully accepted! thank you!

**Comment by MichaelSolati** [comment]
I mean technically this can be used on an express server, I mean you do seem to have this supported, but I'd be inclined to advise that you don't try to query before you render the page. You can however use the `.on('ready', cb)` to see when a query ends and then render the page.
