### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by KelvinPac** [MichaelSolati/geofirestore#8]
Cheers for this awesome library, I have already tried it and it was awesome. I am storing the geofirestore locations on the same collection so doing a query will return me the document snapshots. Is there a way to limit the results just like in Firestore? And is there a way I would pass another Firestore query to geofirestore so that it would also order the results or sort them in a certain way using the other database fields just as we can do in Firestore. 
Thanks.

**Comment by KelvinPac** [comment]
With the current setup I found the library using, if am storing the geofirestore locations on the same collection as my documents, doing a query will return all documents which match, but on large collections the results may be huge. Will we be seeing some kind of pagination or something similar soon? . Am already using this awesome lib in production

**Comment by MichaelSolati** [comment]
It's in my plans for version 2.0.0 or 2.1.0 However there will be a lot of changes come 2.x.x, so keep that in mind.

**Comment by ZenPylon** [comment]
I also am interested in additional querying capability.  I have a tight timeline for an app I'm trying to develop, so I might create a fork and give it a shot.  Would love to hear if you already have any ideas on implementation, but I'll probably try to allow access to the generated query somehow.  I think query criteria are chainable in Firestore?

Anyway, thanks so much for developing this library!  Looks like you've put quite a bit of work in!

**Comment by MvRemmerden** [comment]
Any of you already started working on this? If not, I might take a shot at it, being able to limit the query in order to not exhaust my spark limits within a couple of hours will be critical for me.

**Comment by ZenPylon** [comment]
@MvRemmerden Haven't had a chance yet -- go for it!

**Comment by MichaelSolati** [comment]
[Oh... What's this?](https://github.com/MichaelSolati/geofirestore/commit/05bccde507f94a230c986cc8ea70240e8671e0fe)

**Comment by MvRemmerden** [comment]
That looks amazing, will be the first thing I'm going to test tomorrow morning. Thanks! 😃

**Comment by MvRemmerden** [comment]
I'm actually struggling a bit to get this implemented, would it be possible to post a quick example of how to do this?

**Comment by MichaelSolati** [comment]
@MvRemmerden I've had to make a few changes, but if you wanted to test it now you can `npm i MichaelSolati/geofirestore/v2.1.0`. Note that for your query functions you'll need to refer to the field in your object starting with `d.` and index your database on that field.

You may wanna peak at this [query](https://github.com/MichaelSolati/geofirestore/blob/v2.1.0/test/query.test.ts#L108) and this [index](https://github.com/MichaelSolati/geofirestore/blob/v2.1.0/firestore.indexes.json)

**Comment by MichaelSolati** [comment]
Custom queries should now be working! Try `npm i geofirestore@2.1.0`

It'll be worth reading the [docs here](https://github.com/MichaelSolati/geofirestore/blob/dev/README.md#geofirestorequeryquerycriteria)
