### ISSUE TITLE
Firebase functions integration

### ISSUE THREAD

**Issue by stubborncoder** [MichaelSolati/geofirestore#9]
Hello, I'm still struggling with this, maybe you can help, 

![image](https://user-images.githubusercontent.com/11727994/41499623-35c63e46-7183-11e8-8f16-ff7e7669f10b.png)

When I execute 'npm run build' no matter if I comment out the firebase import, it will trigger the following error that I googled and couldn't find any specific answer, the error will only dissapear if I comment out the geofirestore import...

![image](https://user-images.githubusercontent.com/11727994/41499629-5734f3a6-7183-11e8-8e0c-f92bfc9fd624.png)

package.json

"dependencies": {
    "firebase": "^5.0.4",
    "firebase-admin": "~5.12.1",
    "firebase-functions": "^1.0.4",
    "geofirestore": "^1.2.0"
  },

**Comment by MichaelSolati** [comment]
I don't think this is a Geofirestore question as much as this is a Firebase Functions question. Either way, I'd tell you to do more research and reading the docs of firebase functions, because you dont need to `import * as firebase from 'firebase';` And if you need to create a collectionref for geofirestore you could do...

```
import * as admin from 'firebase-admin';

const collectionRef = admin.firestore().collection('collection');
```

**Comment by stubborncoder** [comment]
I know that admin is the normal way to query collections un cloud functions however if you try to assign that collectionRef to a new Geofirestore(collectionRef), you will get a casting error as Geofirestore  "firebase.firestore.CollectionReference", firebase-admin's collection type "FirebaseFirestore.CollectionReference", In another thread @invention7 sugested to import firebase package instead of admin, but as I show you before even importing Geofirestore as its simplest way throws that error at build.

**Comment by invention7** [comment]
I agree with @stubborncoder that firebase-admin's 'collection' type appears to be incompatible with the collection type expected by the geofirestore constructor.  To get around this, I created by collectionRef with the 'firebase' library.  

Maybe, @MichaelSolati , there is an opportunity for Geofirestore in expanding the constructor to allow the firebase-admin's collection... but in terms of David's immediate need, I think it can be handled as-s.

@stubborncoder, in your firebase config, have you disabled persistence?

e.g. 
PersistenceEnabled: false
?

**Comment by stubborncoder** [comment]
Hi @invention7 my firebaseconfig wasn't modified at all, it's just as it's created by the firebase CLI... thanks for your help!

**Comment by MichaelSolati** [comment]
I'd be open to a PR if anyone wants to expand the types allowed. I'd also ask that the PR is made towards the `dev` branch.

**Comment by invention7** [comment]
Hey @stubborncoder, sorry I missed your comment...  try downgrading firebase to '5.0.0'

**Comment by MichaelSolati** [comment]
In general I can probably double type everything (it would just take a while to get through). You should also be able to `// @ts-ignore` type issues for now. While it's not the end all be all solution, it should work until I dual type everything.

**Comment by stubborncoder** [comment]
@invention7  that did the trick m8, I downgraded as you suggested and now it builds and runs without any further issues!. Thank you very much!.

**Comment by invention7** [comment]
np @stubborncoder !  Good luck!!

**Comment by invention7** [comment]
oh wow!  awesome @MichaelSolati !

**Comment by MichaelSolati** [comment]
Thank you @invention7 !

For everyone else, Firebase Functions should work (may need to make a small patch, but for the most part it's good to go). Try `npm i geofirestore@2.1.0`
